### ISSUE TITLE
How to support flag overrides for next-*

### ISSUE THREAD

**Issue by matthew-andrews** [commuterjoy/fastly-deploy-nodejs#3]
How does something like this sound:-
- A tool like http://app.ft.com/qatool that lists the flags with their default states and buttons to override. [maybe with origami tech docs]
- … which sets cookies in the form something like `next-flag-{flagname}=true`.
- … which fastly reworks to be headers something like `X-Next-Flag-{flagname}: true`, which are stripped out on deliver
- … the express app, if it wants to vary on a flag it sets `res.vary(['Accept-Encoding', 'X-Next-Flag-Ads']);`

cc @richard-still-ft @wheresrhys @commuterjoy @laurent-muchacho @adgad @leanne1

**Comment by commuterjoy** [comment]
@matthew-andrews 

> which sets cookies in the form something like next-flag-{flagname}=true

We could use a single cookie, Eg. `next-flags=adverts,video,byline...` but unless VCL makes it easy to expand this format to x-headers (which I doubt) then stick with lots of cookies.

> which fastly reworks to be headers something like X-Next-Flag-{flagname}: true

Yes. If we need to route based on flag (which we do i think) then the flags need expanding in to x- headers.
